# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean test'
    options: '-Dorg.gradle.java.home=/usr/lib/jvm/java-11-openjdk-amd64'  # Ajusta según la versión de Java
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'JUnit and Cucumber Test Results'