# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '11'
    addToPath: true

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKPath'  # Cambiado a 'JDKPath' para especificar la ruta del JDK
    jdkDirectory: '/usr/lib/jvm/zulu-11-amd64'  # Actualiza la ruta del JDK según tu configuración

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '**/build/jacocoHtml'